#!/usr/bin/python3
import os

class ControlParser():
    def __init__(self):
        try:
            fp = open('debian/control', 'r', encoding='utf-8')
        except IOError:
            raise Exception('cannot find debian/control file')
        self.lines = fp.readlines()
        self.packages = {}
        self.source_name = None

    def load_info(self):
        for line in self.lines:
            if line.lower().startswith('package:'):
                self.packages[line[8:].strip()] = {}
            elif line.lower().startswith('source:'):
                self.source_name = line[7:].strip()

class DHelper():
    def __init__(self):
        self.debian_po_dest = "pofiles"
        self.default_path = "lliurex-po"

    def check_dest(self, packages, source_name):
        if os.path.exists(os.path.join('debian',self.debian_po_dest)):
            if source_name in packages.keys():
                packages[source_name]['pofiles'] = os.path.join('debian',self.debian_po_dest)
                packages[source_name]['i18n'] = []

        for pkg in packages.keys():
            if os.path.exists(os.path.join('debian',pkg + "." + self.debian_po_dest)):
                packages[pkg]['pofiles'] = os.path.join('debian',pkg + "." + self.debian_po_dest)
                packages[pkg]['i18n'] = []
        
        return packages
    
    def check_default_path(self,packages):
        if os.path.exists(self.default_path):
            for pkg in os.listdir(self.default_path):
                print("por aqui")
                print(packages.keys())
                if pkg in packages.keys():
                    print("por alla")
                    aux = {}
                    aux['po_folder'] = os.path.join(self.default_path,pkg)
                    aux['textdomain'] = pkg
                    packages[pkg]['i18n'].append(aux)
        return packages

    def get_po_orig(self, packages):
        for pkg in packages.keys():
            if 'pofiles' in packages[pkg].keys():
                with open(packages[pkg]['pofiles'], 'r', encoding='utf-8') as fd:
                    for line in fd:
                        data = line.split(" ")
                        aux = {}
                        aux['textdomain'] = data[0]
                        aux['po_folder'] = data[1:]
                        packages[pkg]['i18n'].append(aux)
        return packages


        
def main():
    control = ControlParser()
    dhelper = DHelper()
    control.load_info()
    pkg_info = dhelper.check_dest(control.packages, control.source_name)
    print(dhelper.check_default_path(pkg_info))
    dhelper.get_po_orig(pkg_info)
    print(pkg_info)
    
    
    


if __name__ == '__main__':
    main()