#!/usr/bin/python3
import os

class ControlParser():
    def __init__(self):
        try:
            fp = open('debian/control', 'r', encoding='utf-8')
        except IOError:
            raise Exception('cannot find debian/control file')
        self.lines = fp.readlines()
        self.packages = {}
        self.source_name = None

    def load_info(self):
        for line in self.lines:
            if line.lower().startswith('package:'):
                self.packages[line[8:].strip()] = {}
            elif line.lower().startswith('source:'):
                self.source_name = line[7:].strip()

class DHelper():
    def __init__(self):
        self.debian_po_dest = "pofiles"
        self.default_path = "lliurex-po"

    def check_dest(self, packages, source_name):
        if os.path.exists(os.path.join('debian',self.debian_po_dest)):
            if source_name in packages.keys():
                packages[source_name]['pofiles'] = os.path.join('debian',self.debian_po_dest)

        for package in packages.keys():
            if os.path.exists(os.path.join('debian',package + "." + self.debian_po_dest)):
                packages[package]['pofiles'] = os.path.join('debian',package + "." + self.debian_po_dest)
        
        return packages
    
    def check_default_path(self,packages):
        if os.path.exists(self.default_path):
            for x in os.listdir(self.default_path):
                if x in packages.items():
                    packages[x]['po_folder'] = os.path.join(self.default_path,x)
                    packages[x]['textdomain'] = x
        return packages

        
def main():
    control = ControlParser()
    dhelper = DHelper()
    control.load_info()
    print(dhelper.check_dest(control.packages, control.source_name))
    
    
    


if __name__ == '__main__':
    main()